# Version of docker-compose
version: '3'

services:
  # getting postgres DB
  db:
    image: postgres:11.1
    #container_name: troparo_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: troparo
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - troparo


  # getting troparo image
  webservice:
    image: troparo_app
    #container_name: troparo_app
    build: .
    ports:
     - 8080:8080
    depends_on:
      - db
    networks:
      - troparo

       # getting troparo image
  mailapp:
    image: mail_app
    #container_name: library_app
    build: ../mail3/.
    ports:
        - 8085:8080
    depends_on:
      - webservice
    networks:
      - troparo


    # getting troparo image
  webapp:
    image: library_app
    #container_name: library_app
    build: ../webo/library/.
    ports:
        - 8090:8080
    depends_on:
      - webservice
    networks:
      - troparo


volumes:  
  pg-data:

networks:
  troparo:

