# Version of docker-compose
version: '3'

services:
  db:
    image: postgres:11.1
    container_name: troparo_db
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: troparo
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    image: troparo_app
    container_name: troparo_app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pgdata: